--web初始化sql语句

--系统用户表
CREATE TABLE T_SYS_USER(
ID VARCHAR2(32) not null,
USERNAME VARCHAR2(100) not null,
PASSWORD VARCHAR2(32) not null,
IS_SYSTEM CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE not null,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);

--系统角色表
CREATE TABLE T_SYS_ROLE(
ID VARCHAR2(32) not null,
ROLE_MENU VARCHAR2(32) not null,
ROLE_NAME VARCHAR2(100) not null,
DEPT_ID VARCHAR2(32) not null,
DEPT_NAME VARCHAR2(100) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);

--系统账号表
CREATE TABLE T_SYS_ACCOUNT(
ID VARCHAR2(32) not null,
LOGIN_ACCOUNT VARCHAR2(32),
LOGIN_PASSWORD VARCHAR2(32),
LOGIN_TYPE CHAR(2),
CONTACT_PHONE VARCHAR2(50),
CONTACT_EMAIL VARCHAR2(100),
USER_ID VARCHAR2(32),
USER_NAME VARCHAR2(100),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);

--系统资源表
CREATE TABLE T_SYS_MENU(
ID VARCHAR2(32) not null,
MENU_NAME VARCHAR2(32),
PARENT_MENU_ID VARCHAR2(32),
MENU_URL VARCHAR2(100),
ICON_ID VARCHAR2(32),
MENU_LEVEL CHAR(2),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);

--系统部门表
CREATE TABLE T_SYS_DEPT(
ID VARCHAR2(32) not null,
DEPT_NAME VARCHAR2(100),
PARENT_DEPT_NAME VARCHAR2(32),
DEPT_TYPE CHAR(2),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);

--系统角色帐号表
CREATE TABLE T_SYS_ROLE_ACCOUNT(
ID VARCHAR2(32) not null,
ROLE_ID VARCHAR2(32) not null,
ACCOUNT_ID VARCHAR2(32) not null
);

--系统角色菜单表
CREATE TABLE T_SYS_ROLE_MENU(
ID VARCHAR2(32) not null,
ROLE_ID VARCHAR2(32) not null,
MENU_ID VARCHAR2(32) not null,
ACTIONS VARCHAR2(32)
);

--系统部门用户表
CREATE TABLE T_SYS_DEPT_USER(
ID VARCHAR2(32) not null,
DEPT_ID VARCHAR2(32) not null,
USER_ID VARCHAR2(32) not null
);

--系统图标表
CREATE TABLE T_SYS_ICON(
ID VARCHAR2(32) not null,
ICON_NAME VARCHAR2(100) not null,
ICON_TYPE CHAR(2) not null,
ICON_PATH VARCHAR2(100) not null,
ICON_CONTENT VARCHAR2(200),
ICON_CLS VARCHAR2(200),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);


--系统日志表
CREATE TABLE T_SYS_LOG(
ID VARCHAR2(32) not null,
LOG_TYPE CHAR(2) not null,
OPERATION_ACCOUNT VARCHAR2(32) not null,
APERATION_USERNAME VARCHAR2(100),
OPERATION_PATH VARCHAR2(100) not null,
OPERATION_TIME DATE not null,
OPERATION_IP VARCHAR2(50) not null,
LOG_CONTENT VARCHAR2(200)
);

--系统字典表
CREATE TABLE T_SYS_DICT(
ID VARCHAR2(32) not null,
PARENT_ID VARCHAR2(32),
DICT_NO VARCHAR2(32) not null,
DICT_NAME VARCHAR2(100) not null,
DICT_TYPE CHAR(2) not null,
ORDER_NO VARCHAR(4),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);


--系统配置表
CREATE TABLE T_SYS_CONFIG(
ID VARCHAR2(32) not null,
CONFIG_KEY VARCHAR2(32) not null,
CONFIG_TYPE CHAR(2) not null,
CONFIG_NAME VARCHAR2(100) not null,
CONFIG_VALUE VARCHAR2(200) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);


--系统在线用户表
CREATE TABLE T_SYS_ONLINE_USER(
ID VARCHAR2(32) not null,
SESSION_ID VARCHAR2(100) not null,
LOGIN_ACCOUNT VARCHAR2(32) not null,
LOGIN_USER_NAME VARCHAR2(100),
LOGIN_IP VARCHAR2(100) not null,
LOGIN_TIME DATE not null,
LOGIN_URL VARCHAR2(200)
);

--系统操作功能表
CREATE TABLE T_SYS_ACTION(
ID VARCHAR2(32) not null,
ACTION_NO VARCHAR2(32) not null,
ACTION_NAME VARCHAR2(100) not null,
ACTION_TYPE CHAR(2) not null,
ACTION_CONTENT VARCHAR(200),
MENU_ID VARCHAR2(32) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);


--系统通知表
CREATE TABLE T_SYS_NOTIFY(
ID VARCHAR2(32) not null,
NOTIFY_TYPE CHAR(2) not null,
NOTIFY_ADDRESS VARCHAR2(200) not null,
NOTIFY_CONTENT VARCHAR2(200) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR2(32) not null,
UPDATE_UID VARCHAR2(32),
CHECK_UID VARCHAR2(32),
CHECK_FLAG CHAR(1) not null
);
