-----------≥ı ºªØ”Ôæ‰
insert into T_SYS_ACCOUNT(
ID,LOGIN_ACCOUNT,LOGIN_PASSWORD,LOGIN_TYPE,CONTACT_PHONE,CONTACT_EMAIL,USER_ID,USER_NAME,IS_SYSTEM,IS_CLOSE,CREATE_TIME,CHECK_TIME,CREATE_UID,UPDATE_UID,CHECK_FLAG)
values(
SEQ_T_SYS_ACCOUNT_ID.NEXTVAL,'admin','admin','1','18321586198','immerser@163.com','1','lance','0','0',systimestamp,systimestamp,'1','1','1');

insert into T_SYS_ROLE(
ID,ROLE_MENU,ROLE_NAME,DEPT_ID,DEPT_NAME,IS_SYSTEM,IS_CLOSE,CREATE_TIME,CHECK_TIME,CREATE_UID,UPDATE_UID,CHECK_UID,CHECK_FLAG)
VALUES(
SEQ_T_SYS_ROLE_ID.NEXTVAL,'/login','ADMIN','1','tech','0','0',systimestamp,systimestamp,'1','1','1','1');

insert into T_SYS_ROLE_ACCOUNT(
ID,ROLE_ID,ACCOUNT_ID)
VALUES(
SEQ_T_SYS_ROLE_ACCOUNT_ID.NEXTVAL,'1','1');
