
CREATE TABLE T_SYS_USER(
ID int primary key auto_increment not null,
USERNAME VARCHAR(100) not null,
PASSWORD VARCHAR(32) not null,
IS_SYSTEM CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE not null,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_ROLE(
ID int primary key auto_increment not null,
ROLE_MENU VARCHAR(32) not null,
ROLE_NAME VARCHAR(100) not null,
DEPT_ID VARCHAR(32) not null,
DEPT_NAME VARCHAR(100) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_ACCOUNT(
ID int primary key auto_increment not null,
LOGIN_ACCOUNT VARCHAR(32),
LOGIN_PASSWORD VARCHAR(32),
LOGIN_TYPE CHAR(2),
CONTACT_PHONE VARCHAR(50),
CONTACT_EMAIL VARCHAR(100),
USER_ID VARCHAR(32),
USER_NAME VARCHAR(100),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_MENU(
ID int primary key auto_increment not null,
MENU_NAME VARCHAR(32),
PARENT_MENU_ID VARCHAR(32),
MENU_URL VARCHAR(100),
ICON_ID VARCHAR(32),
MENU_LEVEL CHAR(2),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_DEPT(
ID int primary key auto_increment not null,
DEPT_NAME VARCHAR(100),
PARENT_DEPT_NAME VARCHAR(32),
DEPT_TYPE CHAR(2),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_ROLE_ACCOUNT(
ID int primary key auto_increment not null,
ROLE_ID VARCHAR(32) not null,
ACCOUNT_ID VARCHAR(32) not null
);

CREATE TABLE T_SYS_ROLE_MENU(
ID int primary key auto_increment not null,
ROLE_ID VARCHAR(32) not null,
MENU_ID VARCHAR(32) not null,
ACTIONS VARCHAR(32)
);

CREATE TABLE T_SYS_DEPT_USER(
ID int primary key auto_increment not null,
DEPT_ID VARCHAR(32) not null,
USER_ID VARCHAR(32) not null
);

CREATE TABLE T_SYS_ICON(
ID int primary key auto_increment not null,
ICON_NAME VARCHAR(100) not null,
ICON_TYPE CHAR(2) not null,
ICON_PATH VARCHAR(100) not null,
ICON_CONTENT VARCHAR(200),
ICON_CLS VARCHAR(200),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_LOG(
ID int primary key auto_increment not null,
LOG_TYPE CHAR(2) not null,
OPERATION_ACCOUNT VARCHAR(32) not null,
APERATION_USERNAME VARCHAR(100),
OPERATION_PATH VARCHAR(100) not null,
OPERATION_TIME DATE not null,
OPERATION_IP VARCHAR(50) not null,
LOG_CONTENT VARCHAR(200)
);

CREATE TABLE T_SYS_DICT(
ID int primary key auto_increment not null,
PARENT_ID VARCHAR(32),
DICT_NO VARCHAR(32) not null,
DICT_NAME VARCHAR(100) not null,
DICT_TYPE CHAR(2) not null,
ORDER_NO VARCHAR(4),
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);

CREATE TABLE T_SYS_CONFIG(
ID int primary key auto_increment not null,
CONFIG_KEY VARCHAR(32) not null,
CONFIG_TYPE CHAR(2) not null,
CONFIG_NAME VARCHAR(100) not null,
CONFIG_VALUE VARCHAR(200) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);


CREATE TABLE T_SYS_ONLINE_USER(
ID int primary key auto_increment not null,
SESSION_ID VARCHAR(100) not null,
LOGIN_ACCOUNT VARCHAR(32) not null,
LOGIN_USER_NAME VARCHAR(100),
LOGIN_IP VARCHAR(100) not null,
LOGIN_TIME DATE not null,
LOGIN_URL VARCHAR(200)
);

CREATE TABLE T_SYS_ACTION(
ID int primary key auto_increment not null,
ACTION_NO VARCHAR(32) not null,
ACTION_NAME VARCHAR(100) not null,
ACTION_TYPE CHAR(2) not null,
ACTION_CONTENT VARCHAR(200),
MENU_ID VARCHAR(32) not null,
IS_SYSTEM CHAR(1) not null,
IS_CLOSE CHAR(1) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);


CREATE TABLE T_SYS_NOTIFY(
ID int primary key auto_increment not null,
NOTIFY_TYPE CHAR(2) not null,
NOTIFY_ADDRESS VARCHAR(200) not null,
NOTIFY_CONTENT VARCHAR(200) not null,
CREATE_TIME DATE not null,
CHECK_TIME DATE,
CREATE_UID VARCHAR(32) not null,
UPDATE_UID VARCHAR(32),
CHECK_UID VARCHAR(32),
CHECK_FLAG CHAR(1) not null
);
